[package]
name = "gpgagent"
version = "0.1.0"
authors = ["raf"]
repository = "https://github.com/equalsraf/assuan-rs"
license = "ISC"

[dependencies]
unix_socket = "0.5"
rustc-serialize = "0.3"
libc = "0.2"

[dependencies.assuan]
path = "../assuan"
