[package]
name = "assuan"
version = "0.1.0"
description = "Assuan protocol implementation"
repository = "https://github.com/equalsraf/assuan-rs"
license = "ISC"

[dependencies]
url = "1.2"
log = "0.3"

